# Generated by Django 5.0.1 on 2024-01-25 05:46

import django.db.models.deletion
import lyingbard.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.PositiveIntegerField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='lyingbard_speakers')),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(lyingbard.models.IDMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.PositiveIntegerField(editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='lyingbard_generations')),
                ('text', models.TextField(default='')),
                ('gen_date', models.DateTimeField(auto_now_add=True, verbose_name='date generated')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lyingbard.speaker')),
            ],
            bases=(lyingbard.models.IDMixin, models.Model),
        ),
    ]
