# Generated by Django 5.0.1 on 2024-02-07 01:59

import django.db.models.deletion
import lyingbard.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyingbard', '0003_alter_generation_owner_alter_speaker_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TTSModel',
            fields=[
                ('id', models.PositiveIntegerField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='lyingbard_models')),
                ('owner', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('speaker', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='lyingbard.speaker')),
            ],
            bases=(lyingbard.models.IDMixin, models.Model),
        ),
    ]
