# Generated by Django 5.0.1 on 2024-02-23 18:24

import storages.backends.gcloud
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyingbard', '0004_ttsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generation',
            name='file',
            field=models.FileField(upload_to='', verbose_name=storages.backends.gcloud.GoogleCloudStorage(bucket_name='lyingbard-generations')),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='file',
            field=models.FileField(storage=storages.backends.gcloud.GoogleCloudStorage(bucket_name='lyingbard-speakers'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='ttsmodel',
            name='file',
            field=models.FileField(storage=storages.backends.gcloud.GoogleCloudStorage(bucket_name='lyingbard-models'), upload_to=''),
        ),
    ]
