# Generated by Django 5.0.1 on 2024-02-23 19:45

import lyingbard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyingbard', '0005_alter_generation_file_alter_speaker_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generation',
            name='id',
            field=models.PositiveIntegerField(default=lyingbard.models.IDMixin.unique_random_id, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='id',
            field=models.PositiveIntegerField(default=lyingbard.models.IDMixin.unique_random_id, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ttsmodel',
            name='id',
            field=models.PositiveIntegerField(default=lyingbard.models.IDMixin.unique_random_id, editable=False, primary_key=True, serialize=False),
        ),
    ]
