# Generated by Django 5.0.1 on 2024-02-25 19:15

import lyingbard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyingbard', '0006_alter_generation_id_alter_speaker_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generation',
            name='id',
            field=models.PositiveIntegerField(default=lyingbard.models.Generation.unique_random_id, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='id',
            field=models.PositiveIntegerField(default=lyingbard.models.Speaker.unique_random_id, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ttsmodel',
            name='id',
            field=models.PositiveIntegerField(default=lyingbard.models.TTSModel.unique_random_id, editable=False, primary_key=True, serialize=False),
        ),
    ]
