# Generated by Django 5.0.1 on 2024-02-25 19:41

import functools
import lyingbard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyingbard', '0007_alter_generation_id_alter_speaker_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generation',
            name='id',
            field=models.PositiveIntegerField(default=functools.partial(lyingbard.models.IDMixin.lazy_unique_random_id, *('lyingbard.Generation',), **{}), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='id',
            field=models.PositiveIntegerField(default=functools.partial(lyingbard.models.IDMixin.lazy_unique_random_id, *('lyingbard.Speaker',), **{}), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ttsmodel',
            name='id',
            field=models.PositiveIntegerField(default=functools.partial(lyingbard.models.IDMixin.lazy_unique_random_id, *('lyingbard.TTSModel',), **{}), editable=False, primary_key=True, serialize=False),
        ),
    ]
