# Generated by Django 5.0.1 on 2024-02-26 05:18

import storages.backends.gcloud
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyingbard', '0008_alter_generation_id_alter_speaker_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generation',
            name='file',
            field=models.FileField(storage=storages.backends.gcloud.GoogleCloudStorage(bucket_name='lyingbard-generations'), upload_to=''),
        ),
    ]
