# Generated by Django 5.0.1 on 2024-03-07 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lyingbard', '0009_alter_generation_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speaker',
            options={'permissions': [('speakers_create', 'Can create LyingBard speakers')]},
        ),
    ]
