# Generated by Django 5.0.1 on 2024-03-07 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lyingbard', '0010_alter_speaker_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speaker',
            options={'permissions': [('lyingbard_speakers_create', 'Can create LyingBard speakers')]},
        ),
    ]
